#+title: Reference

~spago.nix~ offers a number of functions providing Nix integration for Spago projects. These are contained in a top-level ~spago-nix~ namespace that can be accessed by applying its overlay (~overlays.default~ provided by the ~spago.nix~ flake). This document provides an overview of the different library functions and data structures that are made available.

* Table of Contents :toc:
- [[#top-level-attributes][Top-level attributes]]
  - [[#spago-nixspagoproject][~spago-nix.spagoProject~]]
- [[#library-functions][Library functions]]
  - [[#bundlemodule][~bundleModule~]]
  - [[#bundleapp][~bundleApp~]]
  - [[#runtest][~runTest~]]
  - [[#runtestwithargs][~runTestWithArgs~]]
  - [[#nodeapp][~nodeApp~]]
  - [[#nodeappwithargs][~nodeAppWithArgs~]]
  - [[#builddocs][~buildDocs~]]
- [[#other][Other]]

* Top-level attributes
** ~spago-nix.spagoProject~
This is the primary interface to working with ~spago.nix~. It takes a ~src~ containing a Purescript project and generates several useful flake outputs along with several functions (see [[#library-functions][below]])
*** Arguments
- ~name~ :: (*Required*)
  - Type :: /string/
  - Description :: The project name. Used to set the names of derivations generated in ~spagoProject~

- ~src~ :: (*Required*)
  - Type :: /path/
  - Description :: A Nix store path pointing to the project sources

- ~shell~ ::
  - Type :: /attribute set/
  - Description :: Holds configuration options for the generated ~devShell~. The ~devShell~ will always contain a suitable version of ~purs~ and ~spago~
  - Default ::
    #+begin_src nix
    {
      # Purescript development tools, one of
      # `purs-tidy`, `purty`, `purescript-language-server`, `pscid`
      tools = [ ];
      # Corresponds to `packages` argument of `pkgs.mkShell`
      packages = [ ];
      # If `true`, the Spago packages will be installed in `./.spago` in
      # the `devShell`'s `shellHook`
      install = true;
      # If `true`, `npm install` will only write to `package-lock.json`
      # (and never to `node_modules`)
      packageLockOnly = true;
      # Gets appended to the `shellHook` created for you in the `devShell`
      shellHook = "";
    }
    #+end_src
  - Example ::
    #+begin_src nix
    {
      packages = [ "psa" "purs-tidy" "purescript-language-server" ];
      packageLockOnly = false;
      shellHook = ''
        echo 'my shell hook'
      '';
    }
    #+end_src

- ~extraSources~ ::
  - Type :: /attribute set/
  - Description :: A mapping from dependency names to their sources. Can be easily converted from flake ~inputs~
    *Note*: The sources provided must match the revisions in your ~packages.dhall~ /exactly/. Otherwise hard-to-debug errors will likely arise
  - Default ::
    #+begin_src nix
    { }
    #+end_src
  - Example ::
    #+begin_src nix
    {
      inherit (inputs) foo bar;
    }
    #+end_src

- ~sha256map~ ::
  - Type :: /attribute set/
  - Description :: A mapping from dependency names to their sha256 hashes and exact revisions. Can also be converted from flake ~inputs~
    *Note*: It is considerably more convenient and efficient to use ~extraSources~, as the corresponding dependencies will be fetched from the network when using ~sha256map~
  - Default ::
    #+begin_src nix
    { }
    #+end_src
  - Example ::
    #+begin_src nix
    {
      foo = {
        inherit (inputs.foo) rev;
        sha256 = inputs.foo.narHash;
      };
    }
    #+end_src

- ~flags~ ::
  - Type :: /attribute set/
  - Description :: Contains various flags used for compiling the project sources and installing dependencies
  - Default ::
    #+begin_src nix
    {
      # Turns on `--strict` during compilation; corresponds to
      # `psa --strict ...`
      strict = true;
      # List of warnings to silence during compilation. For example
      # `[ "UserDefinedWarning" ]`
      censorCodes = [ ];
      # If set, the generated `node_modules` will also contain all
      # of the `devDependencies` declared in the `package.json`
      development = true;
    }
    #+end_src
  - Example ::
    #+begin_src nix
    {
      censorCodes = [ "UserDefinedWarning" ];
      development = false;
    }
    #+end_src

- ~nodejs~ ::
  - Type :: /derivation/
  - Description :: The specific version of ~nodejs~ to use. Will be used throughout the project components and in the ~devShell~
  - Default ::
    #+begin_src nix
    pkgs.nodejs-14_x
    #+end_src
  - Example ::
    #+begin_src nix
    pkgs.nodejs-18_x
    #+end_src

- ~buildConfig~ ::
  - Type :: /attribute set/
  - Description :: Holds paths to various build configuration files
  - Default ::
    #+begin_src nix
    {
      packagesDhall = src + "/packages.dhall";
      spagoDhall = src + "/spago.dhall";
      packageJson = src + "/package.json";
      packageLock = src + "/package-lock.json";
    }
    #+end_src
  - Example ::
    #+begin_src nix
    {
      spagoDhall = src + "/some/weird/path/spago.dhall";
    }
    #+end_src

- ~withDocs~ ::
  - Type :: /boolean/
  - Description :: If ~true~, ~spagoProject~ will build docs using default values for options and add them to the ~flake~ attribute that is returned. Even if this is ~false~, you can still use the ~buildDocs~ builder to generate documentation
  - Default ::
    #+begin_src nix
    true
    #+end_src
  - Example ::
    #+begin_src nix
    false
    #+end_src

* Library functions
** ~bundleModule~
Bundles the project into a CommonJS module using the provided ~main~ module to the output filepath indicated by ~to~
*** Returns
/derivation/
*** Args
- ~main~ ::
  - Type :: /string/
  - Description :: The main Purescript module to bundle (the module name, not a filepath), used as the bundled module's entrypoint
  - Default ::
    #+begin_src nix
    "Main"
    #+end_src
  - Example ::
    #+begin_src nix
    "Package.Module.Main"
    #+end_src

- ~to~ ::
  - Type :: /string/
  - Description :: The target filepath that the bundled module will be written to
  - Default ::
    #+begin_src nix
    "index.js"
    #+end_src
  - Example ::
    #+begin_src nix
    "output.js"
    #+end_src

- ~name~ ::
  - Type :: /string/
  - Description :: Overrides the ~name~ used for the derivation, which is otherwise derived from the ~name~ arg to ~spagoProject~
  - Example ::
    #+begin_src nix
    "my-bundled-module"
    #+end_src

** ~bundleApp~
Bundles the project into an executable that can be run with Node, using the provided ~main~ module to the output filepath indicated by ~to~. *Note*: Although this is bundled into an app, it cannot be run on its own and is mostly useful if you want to use it in another derivation. You will still need to call ~node~ to execute it and set the ~NODE_PATH~ if necessary. You can also use [[#nodeapp][ ~nodeApp~ ]] or [[#nodeappwithargs][ ~nodeAppWithArgs~ ]] which both do these steps for you.
*** Returns
/derivation/
*** Args
- ~main~ ::
  - Type :: /string/
  - Description :: The main Purescript module to bundle (the module name, not a filepath), used as the bundled app's entrypoint
  - Default ::
    #+begin_src nix
    "Main"
    #+end_src
  - Example ::
    #+begin_src nix
    "Package.Module.Main"
    #+end_src

- ~to~ ::
  - Type :: /string/
  - Description :: The target filepath that the bundled app will be written to
  - Default ::
    #+begin_src nix
    "index.js"
    #+end_src
  - Example ::
    #+begin_src nix
    "output.js"
    #+end_src

- ~name~ ::
  - Type :: /string/
  - Description :: Overrides the ~name~ used for the derivation, which is otherwise derived from the ~name~ arg to ~spagoProject~
  - Example ::
    #+begin_src nix
    "my-bundled-app"
    #+end_src

** ~runTest~
Calls the Purescript entrypoint specified by ~testMain~ without writing to ~$out~. Suitable for use as part of your flake ~checks~ (if the returns a non-zero exit code, the check will fail)
*** Returns
/derivation/
*** Args
- ~testMain~ ::
  - Type :: /string/
  - Description :: The main Purescript module that acts as an entrypoint
  - Default ::
    #+begin_src nix
    "Test.Main"
    #+end_src
  - Example ::
    #+begin_src nix
    "Package.Module.Test.Main"
    #+end_src

- ~env~ ::
  - Type :: /attribute set/
  - Description :: Environment or other variables; these are passed directly to ~runCommand~. Can be useful if your test depends on looking up something in the environment
  - Default ::
    #+begin_src nix
    { }
    #+end_src
  - Example ::
    #+begin_src nix
    {
      ENV_VAR = "value";
    }
    #+end_src

- ~nodeModules~ ::
  - Type :: /derivation/
  - Description :: Overrides the ~nodeModules~ used internally, which default to the project-wide ones
  - Example ::
    #+begin_src nix
    spago-nix.utils.js.mkNodeModules {
      development = false;
      /* snip */
    }
    #+end_src

- ~name~ ::
  - Type :: /string/
  - Description :: Overrides the ~name~ used for the derivation, which is otherwise derived from the ~name~ arg to ~spagoProject~
  - Example ::
    #+begin_src nix
    "my-test"
    #+end_src

** ~runTestWithArgs~
Calls the Purescript entrypoint (specified by ~testMain~) with Node and without writing to ~$out~. Provides the specified ~command~ and ~arugments~ to the Node invocation; this is useful if your test requires or parses specific arguments. Also suitable for use as part of your flake ~checks~ (if the returns a non-zero exit code, the check will fail to build)
*** Returns
/derivation/
*** Args
- ~testMain~ ::
  - Type :: /string/
  - Description :: The main Purescript module that acts as an entrypoint
  - Default ::
    #+begin_src nix
    "Test.Main"
    #+end_src
  - Example ::
    #+begin_src nix
    "Package.Module.Test.Main"
    #+end_src

- ~command~ ::
  - Type :: /string/
  - Description :: The command-line name. Node's ~process.env.argv~ includes this as the first argument, so if we didn't include it then the first argument would become the command name (an undesirable result)
  - Default ::
    #+begin_src nix
    builtins.replaceStrings [ "." ] [ "-" ]
      (lib.strings.toLower testMain)
    #+end_src
  - Example ::
    #+begin_src nix
    "my-test"
    #+end_src

- ~arguments~ ::
  - Type :: /list/
  - Description :: The arguments to provide to the command. These are joined into a single space-separated string and passed to the Node invocation
  - Default ::
    #+begin_src nix
    [ ]
    #+end_src
  - Example ::
    #+begin_src nix
    [ "--arg1" "val1" "--arg2" "val2" ]
    #+end_src

- ~env~ ::
  - Type :: /attribute set/
  - Description :: Environment or other variables; these are passed directly to ~runCommand~. Can be useful if your test depends on looking up something in the environment
  - Default ::
    #+begin_src nix
    { }
    #+end_src
  - Example ::
    #+begin_src nix
    {
      ENV_VAR = "value";
    }
    #+end_src

- ~nodeModules~ ::
  - Type :: /derivation/
  - Description :: Overrides the ~nodeModules~ used internally, which default to the project-wide ones
  - Example ::
    #+begin_src nix
    spago-nix.utils.js.mkNodeModules {
      development = false;
      /* snip */
    }
    #+end_src

- ~name~ ::
  - Type :: /string/
  - Description :: Overrides the ~name~ used for the derivation, which is otherwise derived from the ~name~ arg to ~spagoProject~
  - Example ::
    #+begin_src nix
    "my-test"
    #+end_src

** ~nodeApp~
Creates an executable from the Purescript entrypoint (specified by ~main~) that calls Node, installing it to ~$out/bin/name~. This is similar to [[#bundleapp][ ~bundleApp~ ]] above, but calls ~node~ for you and also sets the correct ~NODE_PATH~ using the ~nodeModules~ that have been generated for the project (unless overridden)
*** Returns
/derivation/
*** Args
- ~main~ ::
  - Type :: /string/
  - Description :: The main Purescript module that acts as an entrypoint
  - Default ::
    #+begin_src nix
    "Main"
    #+end_src
  - Example ::
    #+begin_src nix
    "Package.Module.Main"
    #+end_src

- ~env~ ::
  - Type :: /attribute set/
  - Description :: Environment or other variables. These are ~export~ ed in a script that is provided to ~writeShellApplication~, so you may want to use ~escapeShellArg~ as this is not done for you automatically. Can be useful if your test depends on looking up something in the environment
  - Default ::
    #+begin_src nix
    { }
    #+end_src
  - Example ::
    #+begin_src nix
    {
      ENV_VAR = "value";
    }
    #+end_src

- ~nodeModules~ ::
  - Type :: /derivation/
  - Description :: Overrides the ~nodeModules~ used internally, which default to the project-wide ones
  - Example ::
    #+begin_src nix
    spago-nix.utils.js.mkNodeModules {
      development = false;
      /* snip */
    }
    #+end_src

- ~name~ ::
  - Type :: /string/
  - Description :: Overrides the ~name~ used for the derivation, which is otherwise derived from the ~name~ arg to ~spagoProject~
  - Example ::
    #+begin_src nix
    "my-node-app"
    #+end_src

** ~nodeAppWithArgs~
  Similar to [[#nodeapp][ ~nodeApp~ ]] above, but also allows for passing a command name and list of arguments. *Note*: This is useful if you want to call an application with the same set of arguments each time -- specifically, those passed with the provided list of ~arguments~ will always be used
*** Returns
/derivation/
*** Args
- ~main~ ::
  - Type :: /string/
  - Description :: The main Purescript module that acts as an entrypoint
  - Default ::
    #+begin_src nix
    "Main"
    #+end_src
  - Example ::
    #+begin_src nix
    "Package.Module.Main"
    #+end_src

- ~env~ ::
  - Type :: /attribute set/
  - Description :: Environment or other variables. These are ~export~ ed in a script that is provided to ~writeShellApplication~, so you may want to use ~escapeShellArg~ as this is not done for you automatically. Can be useful if your test depends on looking up something in the environment
  - Default ::
    #+begin_src nix
    { }
    #+end_src
  - Example ::
    #+begin_src nix
    {
      ENV_VAR = "value";
    }
    #+end_src

- ~nodeModules~ ::
  - Type :: /derivation/
  - Description :: Overrides the ~nodeModules~ used internally, which default to the project-wide ones
  - Example ::
    #+begin_src nix
    spago-nix.utils.js.mkNodeModules {
      development = false;
      /* snip */
    }
    #+end_src

- ~name~ ::
  - Type :: /string/
  - Description :: Overrides the ~name~ used for the derivation, which is otherwise derived from the ~name~ arg to ~spagoProject~
  - Example ::
    #+begin_src nix
    "my-node-app"
    #+end_src

** ~buildDocs~
  Compiles the project documentation, either solely for dependencies if ~depsOnly~ is enabled, or for all modules including the project sources (the default behavior).
  *Note*: If you set the ~withDocs~ argument to ~true~ (the default value) in [[#spago-nixspagoproject][ ~spagoProject~ ]], a ~docs~ attribute will be built and added to ~flake.packages~.
*** Returns
/derivation/
*** Args
- ~format~ ::
  - Type :: one of "~html~" or "~markdown~"
  - Description :: The format for the resulting compiled documentation
  - Default ::
    #+begin_src nix
    "html"
    #+end_src
  - Example ::
    #+begin_src nix
    "markdown"
    #+end_src

- ~depsOnly~ ::
  - Type :: /boolean/
  - Description :: If ~true~, documentation will only be compiled for the project's dependencies
  - Default ::
    #+begin_src nix
    false
    #+end_src
  - Example ::
    #+begin_src nix
    true
    #+end_src

* Other
